### ISSUE TITLE
GitHub API Pagination support 

### ISSUE THREAD

**Issue by ehsandeep** [lacolaco/contributors-img#837]
Hi,

Thank you for creating and hosting this project, I'm looking to embed this project in GitHub readme for contributors visibility but noticed it only supports 100 users as max, we can add pagination to fetch all contributors from GitHub API, for example- https://github.com/ehpankaj/contributors-img/commit/c3cc2f5750a708627431fd9d5bc58281dee7810b

**Comment by lacolaco** [comment]
@ehsandeep Thanks for the advice. Currently, I'm limiting users up to 100 by design because rendering all contributors in huge repositories by default spends a lot of computing resources. 

But I think it can be solved by something like `?max=120` query params to support that use-case as opt-in. I'll begin working on it in a few weeks.

**Comment by ehsandeep** [comment]
definitely that will help @lacolaco, thank you

**Comment by lacolaco** [comment]
@ehsandeep I've added the `max` param to contributors image URL. For example, `https://contrib.rocks/image?repo=angular/angular-ja&max=50` will work. 
Deployment is in progress. Try it after few hours!

**Comment by ehsandeep** [comment]
Thank you @lacolaco for adding this support.
